#!/usr/bin/env php
<?php

use Tempest\Container\TempestContainer;
use Tempest\Tempest;

require_once getcwd() . '/vendor/autoload.php';

$container = TempestContainer::getInstance();

Tempest::console(container: $container, path: __DIR__)->run();

exit;